version: "3.5"

services:
  app:
    container_name: slack-app-test
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    command: npm run start

  ngrok:
    container_name: zenbot-public-server
    image: wernight/ngrok
    restart: unless-stopped
    ports:
      - 11433:4040
    entrypoint: ngrok http slack-app-test:3000
